---
- name: Weekly System Update
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Check which packages are triggering the reboot (for logging)
      ansible.builtin.slurp:
        src: /var/run/reboot-required.pkgs
      register: reboot_packages
      when: reboot_required_file.stat.exists

    - name: Print the packages which require a reboot
      ansible.builtin.debug:
        msg: "Reboot is required by the following packages: {{ reboot_packages['content'] | b64decode }}"
      when: reboot_required_file.stat.exists

    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_required_file.stat.exists

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: true
        purge: true
