server:
  address: 'tcp4://:9091'

log:
  level: info
  file_path: '/var/log/authelia/authelia.log'
  keep_stdout: true

identity_validation:
  elevated_session:
    require_second_factor: true
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_secret: {{ mustEnv "CUSTOM_AUTHELIA_JWT_SECRET" | mindent 0 "|" | msquote }}

totp:
  disable: false
  issuer: '{{ mustEnv "BASE_DOMAIN" }}'
  period: 30
  skew: 1

password_policy:
  zxcvbn:
    enabled: true
    min_score: 4

authentication_backend:
  ldap:
    implementation: 'lldap'
    address: 'ldap://lldap:3890'
    # base_dn and user are set through env variables
    password: {{ mustEnv "CUSTOM_AUTHELIA_LDAP_PASSWORD" | msquote }}

access_control:
  default_policy: 'deny'
  rules:
    - domain:
        - 'paperless.{{ mustEnv "BASE_DOMAIN" }}'
      resources:
        - '^/admin([/?].*)?$'
      policy: 'two_factor'
      subject: 'group:admin'
    - domain:
        - 'auth.{{ mustEnv "BASE_DOMAIN" }}'
        - 'vw.{{ mustEnv "BASE_DOMAIN" }}'
        - 'immich.{{ mustEnv "BASE_DOMAIN" }}'
        - 'grafana.{{ mustEnv "BASE_DOMAIN" }}'
        - 'jellyfin.{{ mustEnv "BASE_DOMAIN" }}'
        - 'linkwarden.{{ mustEnv "BASE_DOMAIN" }}'
        - 'audiobookshelf.{{ mustEnv "BASE_DOMAIN" }}'
        - 'readeck.{{ mustEnv "BASE_DOMAIN" }}'
        - 'filebrowser-vps.{{ mustEnv "BASE_DOMAIN" }}'
        - 'ldap.{{ mustEnv "BASE_DOMAIN" }}'
        - 'paperless.{{ mustEnv "BASE_DOMAIN" }}'
      policy: 'bypass' # these have their own auth or use OIDC
    - domain: 
        - 'traefik-dashboard.{{ mustEnv "BASE_DOMAIN" }}'
        - 'px-home.{{ mustEnv "BASE_DOMAIN" }}'
        - 'apprise.{{ mustEnv "BASE_DOMAIN" }}'
        - 'backrest.{{ mustEnv "BASE_DOMAIN" }}' 
        - 'grafana.{{ mustEnv "BASE_DOMAIN" }}'
        - 'whoami.{{ mustEnv "BASE_DOMAIN" }}'
        - 'whoami-home.{{ mustEnv "BASE_DOMAIN" }}'
        - 'excalidraw.{{ mustEnv "BASE_DOMAIN" }}'
        - 'gatus.{{ mustEnv "BASE_DOMAIN" }}'
        - 'vs.{{ mustEnv "BASE_DOMAIN" }}'
        - 'whatsapp.{{ mustEnv "BASE_DOMAIN" }}'
        - 'github-release-monitor.{{ mustEnv "BASE_DOMAIN" }}'
        - 'glance.{{ mustEnv "BASE_DOMAIN" }}'
        - 'wiki.{{ mustEnv "BASE_DOMAIN" }}'
        - 'notes.{{ mustEnv "BASE_DOMAIN" }}'
      policy: 'two_factor'
      subject: 'group:admin'
    - domain_regex:
        - '^.+-home\.{{ mustEnv "BASE_DOMAIN" | replace "." "\\." }}$'
      policy: 'two_factor'
      subject: 'group:admin'
    - domain: 
        - 'qbittorrent.{{ mustEnv "BASE_DOMAIN" }}'
        - 'fb-home.{{ mustEnv "BASE_DOMAIN" }}' 
      policy: 'two_factor'
    - domain:
        - 'stirling-pdf.{{ mustEnv "BASE_DOMAIN" }}'
        - 'speedtest.{{ mustEnv "BASE_DOMAIN" }}'
        - 'it-tools.{{ mustEnv "BASE_DOMAIN" }}'
      policy: 'one_factor'

session:
  name: 'authelia_session'
  secret: {{ mustEnv "CUSTOM_AUTHELIA_SESSION_SECRET" | mindent 0 "|" | msquote }}
  inactivity: '5h'
  expiration: '10h'
  remember_me: '20d'
  redis:
    host: 'redis-authelia'
    port: 6379
    timeout: '5s'
    max_retries: 0
    username: default
    password: {{ mustEnv "REDIS_PASSWORD" | mindent 0 "|" | msquote }}
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
  cookies:
    - domain: '{{ mustEnv "BASE_DOMAIN" }}'
      authelia_url: 'https://auth.{{ mustEnv "BASE_DOMAIN" }}'

regulation:
  max_retries: 4
  find_time: '1h'
  ban_time: '2h'

storage:
  encryption_key: {{ mustEnv "CUSTOM_AUTHELIA_STORAGE_ENCRYPTION_KEY" | mindent 0 "|" | msquote }}
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: false
  smtp:
    password: {{ mustEnv "CUSTOM_AUTHELIA_SMTP_PASSWORD" | mindent 0 "|" | msquote }}

definitions:
  user_attributes:
    immich_role:
      expression: '"admin" in groups ? "admin" : "immich-users" in groups ? "user" : ""'

identity_providers:
  oidc:
    ## See: https://www.authelia.com/c/oidc
    hmac_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_HMAC_SECRET" | msquote }}
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/secrets/oidc/jwks/private.pem" | mindent 10 "|" | msquote }}
    claims_policies:
      ## opkssh needs more claims in ID token to be able to verify claims
      opkssh:
        id_token: ['groups']
      immich:
        custom_claims:
          immich_role:
            attribute: immich_role
    enable_client_debug_messages: false
    enforce_pkce: 'public_clients_only'
    authorization_policies:
      proxmox_access:
        default_policy: 'deny'
        rules:
          - policy: 'two_factor'
            subject: 'group:admin'
      immich_access:
        default_policy: 'deny'
        rules:
          - policy: 'two_factor'
            subject: 
            - ['group:admin', 'group:dev']
          - policy: 'one_factor'
            subject: 'group:immich-users'
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
        - 'userinfo'
      allowed_origins:
        - 'https://{{ mustEnv "BASE_DOMAIN" }}'
      allowed_origins_from_client_redirect_uris: false
    scopes:
      immich:
        claims:
          - immich_role
    clients:
      - client_name: 'immich'
        client_id: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_IMMICH_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_IMMICH_CLIENT_SECRET_HASH" | msquote }}
        public: false
        authorization_policy: 'immich_access'
        id_token_signed_response_alg: 'RS256'
        userinfo_signed_response_alg: 'RS256'
        token_endpoint_auth_method: 'client_secret_post'
        redirect_uris:
          - 'https://immich.{{ mustEnv "BASE_DOMAIN" }}/auth/login'
          - 'https://immich.home.{{ mustEnv "BASE_DOMAIN" }}/auth/login'
          - 'https://immich.{{ mustEnv "BASE_DOMAIN" }}/user-settings'
          - 'https://immich.home.{{ mustEnv "BASE_DOMAIN" }}/user-settings'
          - 'app.immich:///oauth-callback'
        claims_policy: immich
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'immich'
        consent_mode: implicit
        pre_configured_consent_duration: '3 months'
      - client_name: 'Grafana'
        client_id: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_GRAFANA_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_GRAFANA_CLIENT_SECRET_HASH" | msquote }}
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://grafana.{{ mustEnv "BASE_DOMAIN" }}/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        consent_mode: implicit
        pre_configured_consent_duration: '3 months'
      - client_name: 'jellyfin'
        client_id: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_JELLYFIN_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_JELLYFIN_CLIENT_SECRET_HASH" | msquote }}
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'two_factor'
        id_token_signed_response_alg: 'RS256'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        consent_mode: implicit
        pre_configured_consent_duration: '3 months'
        redirect_uris:
          - 'https://jellyfin.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/r/authelia'
          - 'http://jellyfin.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/r/authelia'
          - 'https://jellyfin.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/redirect/authelia'
          - 'http://jellyfin.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/redirect/authelia'
          - 'https://jellyfin.home.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/r/authelia'
          - 'http://jellyfin.home.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/r/authelia'
          - 'https://jellyfin.home.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/redirect/authelia'
          - 'http://jellyfin.home.{{ mustEnv "BASE_DOMAIN" }}/sso/OID/redirect/authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
      - client_name: linkwarden
        client_id: {{ mustEnv "LINKWARDEN_OAUTH_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "LINKWARDEN_OAUTH_DIGEST" | msquote }}
        public: false
        authorization_policy: two_factor
        token_endpoint_auth_method: 'client_secret_basic'
        consent_mode: implicit
        pre_configured_consent_duration: '3 months'
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://linkwarden.{{ mustEnv "BASE_DOMAIN" }}/api/v1/auth/callback/authelia
        userinfo_signed_response_alg: none
      - client_name: 'opkssh'
        client_id: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_OPKSSH_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_OPKSSH_CLIENT_SECRET_HASH" | msquote }}
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'http://localhost:3000/login-callback'
          - 'http://localhost:10001/login-callback'
          - 'http://localhost:11110/login-callback'
        scopes:
          - openid
          - groups
          - offline_access
        claims_policy: opkssh
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        id_token_signed_response_alg: 'RS256'
        userinfo_signed_response_alg: 'RS256'
        access_token_signed_response_alg: 'RS256'
        token_endpoint_auth_method: 'client_secret_post'
      - client_name: 'proxmox'
        client_id: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_PROXMOX_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_PROXMOX_CLIENT_SECRET_HASH" | msquote }}
        public: false
        authorization_policy: 'proxmox_access'
        require_pkce: true
        pkce_challenge_method: 'S256'
        consent_mode: implicit
        pre_configured_consent_duration: '2 weeks'
        redirect_uris:
          - 'https://px-home.{{ mustEnv "BASE_DOMAIN" }}'
          - 'https://proxmox.home.{{ mustEnv "BASE_DOMAIN" }}'
          - 'https://proxmox:8006'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
      - client_name: 'paperless-ngx'
        client_id: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_PAPERLESS_CLIENT_ID" | msquote }}
        client_secret: {{ mustEnv "CUSTOM_AUTHELIA_OIDC_PAPERLESS_CLIENT_SECRET_HASH" | msquote }}
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        consent_mode: implicit
        pre_configured_consent_duration: '2 weeks'
        redirect_uris:
          - 'https://paperless.{{ mustEnv "BASE_DOMAIN" }}/accounts/oidc/authelia/login/callback/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
