---
- name: Prune unused Docker images
  hosts: has_docker
  serial: "{{ batch_size | default(1) }}"
  become: true
  tasks:
    - name: Prune unused Docker images
      ansible.builtin.command: docker image prune -a -f
      changed_when: false
