---
ansible_host: "{{ home_network_address if in_home_network is defined and in_home_network | bool else vpn_ip }}"
ansible_ssh_common_args: "{{ '' if in_home_network is defined and in_home_network | bool else ('-o ProxyCommand=\"ssh -W %h:%p -q ' + jump_host_from_internet + '\"')  }}"
wireguard_endpoint: "{{ home_network_address }}"
wireguard_addresses:
  - "{{ vpn_ip }}/32"