---
collections:
  - name: bitwarden.secrets
    version: 1.0.1
    source: https://galaxy.ansible.com

roles:
  - name: githubixx.ansible_role_wireguard
    src: https://github.com/githubixx/ansible-role-wireguard.git
    version: 18.2.0